### ISSUE TITLE
Google Drive spreadsheet and Dropbox not working

### ISSUE THREAD

**Issue by zhouqin1983** [helloworld1/AnyMemo#517]
Tried both, neither works. Google Drive spreadsheet stuck with a white screen with a waiting circle (a small, rotating color circle); and if you go back, it shows error: 

Error
RC_AUTH_TOKEN does not have token

![image](https://user-images.githubusercontent.com/78831853/136244603-e2b13359-8ad1-4eb7-8a4d-55e054ca0ba0.png)

Dropbox shows a long error message:

Connection error
Cannot connect to server. Please check the internet connection.
Exception: java.io.IOException: HTTP request: https://api.dropboxapi.com/2/files/list_folder, response code: 409, response: {"error_summary": "path/ not_found/..", ......

**Comment by helloworld1** [comment]
Thanks for reporting the issue. Drop box seems to work fine on my device. Have you created "anymemo" folder in the dropbox? 

For Google Spreadsheet, Google has removed the API that AnyMemo need. We will, unfortunately, remove the Google Spreadsheet capability in the next version since complying Google's requirement is not open-source friendly. We plan to go back to use F-droid to release once we have removed all the Google's libraries.

**Comment by zhouqin1983** [comment]
I've added anymemo folder in dropbox and it seems to work now.
Sorry to see the removal of support for google spreadsheet.
Thanks a lot for the quick response!!
