### ISSUE TITLE
Publish AnyMemo to main F-Droid repo

### ISSUE THREAD

**Issue by helloworld1** [helloworld1/AnyMemo#519]
@IzzySoft Now AnyMemo is free from Google's non-free libraries. I have also added fastlane changelogs there. I wonder if it is possible to publish AnyMemo back to the main F-Droid repo. Thanks!

**Comment by IzzySoft** [comment]
Confirmed the proprietary libs are fully gone (just updated manually in my repo and checked the scanner results), so [here you go](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9959). Once your app is alive again at F-Droid: what shall happen to its presence in my repo, where it lived in the meantime? Shall I remove it there after the usual proper overlap of about 10 days, or do you want me to keep it there?

**Comment by IzzySoft** [comment]
Umpf:

```
2021-10-23 10:31:52,439 ERROR: Found ZIP file archive at app/src/androidTest/assets/zip-test.zip
2021-10-23 10:31:52,446 ERROR: Could not build app org.liberty.android.fantastischmemo: Can't build due to 1 error while scanning
```

Is that needed for building? Guess not (as it's in `androidTest`, I'll try to remove that via the build recipe. Third round, let's see.

Should you one day remove that ZIP, we'll need to adjust the build recipe once more (or build fails because it cannot remove what's not there – yes, I know and said so myself: gone is gone, so it should "silently ignore" that, simply reporting it as a warning; but someone needs to implement that…)

Gna, [build still fails](https://gitlab.com/IzzySoft/fdroiddata/-/jobs/1708584330). Any ideas?

```
FAILURE: Build failed with an exception.
* What went wrong:
Task 'assembleFreeRelease' not found in project ':app'.
```

**Comment by IzzySoft** [comment]
Thanks to a team member this last issue could be solved (flavor dimensions… well, that's way over my head, not being an Android dev at all). So the change is to be merged soon and the new version should become available at F-Droid within a week, hopefully (or earlier, dreamingly). Waiting for your decision on whether to keep the app in my repo after that.

**Comment by helloworld1** [comment]
Thanks a lot for helping on that. First, you can remove it from your repo if it's increasing your workload is maintaining. And second, you are right about the zip file, it's used for integration test and not needed for main build. I will take note on that file if it is removed or moved in the future. And last, I am very glad to hear that dimension flavor will be supported.

**Comment by IzzySoft** [comment]
Thanks! Merge is through now, so it seems like dimensions can be worked with. As for removing AnyMemo from my repo: [see here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ), both ways have their pros and cons. I usually remove apps from my repo once they reached F-Droid's unless I'm explicitly asked to keep them in mine. It's rarely extra workload in maintaining them (that mostly works automatically), but rather that my repo runs on my "personal resources", which are not "endless" – also one of the reasons I limit each app to 30 MB in size. But if there's stated demand, I see no problems with keeping an app as long as it doesn't exceed those limits :wink:

**Comment by helloworld1** [comment]
Feel free to remove AnyMemo from your repo after it reached F-Droid. Let me know if the dimension flavor can be worked out. If needed, I can try use Gradle to create a task alias from "assembleFreeApi16Release" to "assembleRelease"

**Comment by IzzySoft** [comment]
OK, I'll set a marker then. As soon as the update is through we know it should work as-is (and no changes concerning the dimension flavor are needed), about 10d later I'll remove the app from my repo. Should you need it revived there, just drop me a note: metadata will be retained, so it's rather easily re-established.

**Comment by helloworld1** [comment]
The F-Droid is now updated. I have tested it working correctly. Closing this issue. Thanks again!

**Comment by IzzySoft** [comment]
Gladly – and thanks for the reminder! I just cross-checked and found another minor issue we overlooked: the YAML has still the description inside, which is why your Fastlane is not used at all. I'd remove that on F-Droid's end, but before doing so: our translators put much energy into their work; would you like to accept their `short_description.txt` for another 40 languages into your Fastlane? I'd then prepare a PR for that before cleaning it up at F-Droid.

**Comment by helloworld1** [comment]
Sounds good. For sure I will accept the translations.

**Comment by IzzySoft** [comment]
And there you go! Once merged and the next release being ready, please let me know so I remove the files from F-Droid before the new release will be picked up, making a "gap-less transition" possible.

**Comment by helloworld1** [comment]
Sounds good, will let you know when the next release is ready. Thank you!
